name: .NET

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

env:
  PROJECT_PATH: 'PostService/PostService.csproj'
  TEST_PATH: 'PostService.Tests/PostService.Tests.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ${{ env.TEST_PATH }}
