name: Build Postservice

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

env:
  PROJECT_PATH: 'S3P2_project/PostService/PostService.csproj'
  TEST_PATH: 'S3P2_project/PostService.Tests/PostService.Tests.csproj'

jobs:
  -job: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ${{ env.TEST_PATH }}

  -job: Docker    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: 'S3P2_project/PostService'
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/s3p2_backend:latest
